### ISSUE TITLE
[BUG] Throw proper error in case the user tries to register again with the same email address

### ISSUE THREAD

**Issue by aniri** [code4romania/de-urgenta-backend#61]
If an account is already registered with an email address and the user tries to register again with the same email, an error should be thrown.

**Comment by idormenco** [comment]
For now we do not throw any exception or return a specific error code because it might allow ill-indented people to iterate (using a list of emails) other our users. Will think of a elegant solution to this problem.

**Comment by Alexei000** [comment]
Hey!

One solution for this issue would be to allow for a decent UX (know when an e-mail has been used), but prevent batch testing by using IP rate-limiting ([suggestion source](https://stackoverflow.com/questions/9269040/which-http-response-code-for-this-email-is-already-registered/32531069#32531069)).

I have quickly checked this idea on a fork [here](https://github.com/code4romania/de-urgenta-backend/compare/develop...Alexei000:feature/61-email-already-used-response?expand=1) using [AspNetCoreRateLimit](https://github.com/stefanprodan/AspNetCoreRateLimit) and it seems to work. 

However, I am not sure about returning a Conflict response for existing e-mails. The alternative would be returning OK, but this requires a breaking change for the response payload model since now it is just a string.

**Note:** I found this issue of decent UX vs. security interested and also raised it on [Security SE](https://security.stackexchange.com/questions/256183/is-it-possible-to-avoid-exposing-the-fact-that-an-e-mail-address-is-used-by-a-we).

I have not still checked the clients (SPA, Mobile?) to see how they tackle a non-OK status code for this case.

**Comment by idormenco** [comment]
Hi @Alexei000, thanks for the research and PoC.
Can you please open a PR so other devs can comment and review it .

Thanks
